# Generated by Django 5.2.1 on 2025-06-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collaborateur_id',
            field=models.IntegerField(blank=True, help_text='ID du collaborateur provenant du service externe', null=True),
        ),
    ]
