# Generated by Django 5.2.1 on 2025-06-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_collaborateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collaborateur_id',
            field=models.CharField(blank=True, help_text='ID du collaborateur provenant du service externe', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='statut',
            field=models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='À faire', max_length=20),
        ),
    ]
