# Generated by Django 5.2.1 on 2025-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_collaborateur_id_alter_task_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='statut',
            field=models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='À faire', max_length=20),
        ),
    ]
